package com.tm.coreNetwork.model.gameDetails

import kotlinx.serialization.Serializable

@Serializable
data class GameDetailsResponse(
    val achievements_count: Int,
    val added: Int,
    val added_by_status: AddedByStatusDTO,
    val additions_count: Int,
    val background_image: String,
    val background_image_additional: String,
    val creators_count: Int,
    val description: String,
    val description_raw: String,
    val developers: List<DeveloperDTO>,
    val dominant_color: String,
    val esrb_rating: EsrbRatingDTO,
    val game_series_count: Int,
    val genres: List<GenreDTO>,
    val id: Int,
    val metacritic: Int,
    val metacritic_url: String,
    val movies_count: Int,
    val name: String,
    val name_original: String,
    val parent_achievements_count: Int,
    val parent_platforms: List<ParentPlatformDTO>,
    val parents_count: Int,
    val platforms: List<PlatformXDTO>,
    val playtime: Int,
    val publishers: List<PublisherDTO>,
    val rating: Double,
    val rating_top: Int,
    val ratings: List<RatingDTO>,
    val ratings_count: Int,
    val reddit_count: Int,
    val reddit_description: String,
    val reddit_logo: String,
    val reddit_name: String,
    val reddit_url: String,
    val released: String,
    val reviews_count: Int,
    val reviews_text_count: Int,
    val saturated_color: String,
    val screenshots_count: Int,
    val slug: String,
    val stores: List<StoreDTO>,
    val suggestions_count: Int,
    val tags: List<TagDTO>,
    val tba: Boolean,
    val twitch_count: Int,
    val updated: String,
    val website: String,
    val youtube_count: Int
)